# see https://docs.github.com/en/github/administering-a-repository/customizing-dependency-updates
version: 2
updates:
    - package-ecosystem: npm
      directory: '/'
      schedule:
          interval: daily
      open-pull-requests-limit: 10
      versioning-strategy: increase
    - package-ecosystem: npm
      directory: '/modules/server/'
      schedule:
          interval: daily
      open-pull-requests-limit: 10
      versioning-strategy: increase
    - package-ecosystem: npm
      directory: '/modules/browser/'
      schedule:
          interval: daily
      open-pull-requests-limit: 10
      versioning-strategy: increase
    - package-ecosystem: npm
      directory: '/modules/model/'
      schedule:
          interval: daily
      open-pull-requests-limit: 10
      versioning-strategy: increase
